### ISSUE TITLE
sales return

### ISSUE THREAD

**Issue by tiomuhamedi** [imran300/inventory#1]
Hii.. im so interesting about ur work, this cool and i appreciate this work, i try ur kandi inventory and i can't see sales return menu and in Sales Controller many function for support sales return not found, can u help me for sales return please..

i'll be happy if u want to help me :)

**Comment by imran300** [comment]
>
> Hi
>
yeah I know many people wants sales return but I am kind of busy so I will
try my best to make it ASAP
Thanks for your interest

**Comment by tiomuhamedi** [comment]
thanks brother for ur response... 💯 👍
